from clint.textui import colored
import time
import os
def brute19banner():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████            --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████               --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████                 --V1.1--"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████"""+colored.red("          [")+colored.green("*")+colored.red("]")+colored.cyan("[Choose A Website]")))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████"""+colored.red("              [")+colored.green("1")+colored.red("]")+"Instagram"))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""+colored.red("              [")+colored.green("2")+colored.red("]")+"Facebook"))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""+colored.red("              [")+colored.green("3")+colored.red("]")+"Twitter"))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████"""))
def normal_banner():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████            --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████               --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████                 --V1.1--"""))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████\n\n"""))

